# Build stage
FROM node:20-alpine AS build
WORKDIR /retab-client
COPY package*.json ./
RUN npm ci
COPY . .
COPY ./.env.musica ./.env.production

RUN npm run build


# Production stage
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /retab-client/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]